# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the workflow will run
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: mkdir ./build/
      - run: ls .
      - run: cd ./build/
      - run: ls ../
      - run: pacman -Sy asp base-devel --noconfirm
      - run: asp update linux
      - run: asp export linux
      - run: ls ../
      - run: patch ./linux/config/PKGBUILD ../pkgbuild.patch
      - run: cat ./linux/config/PKGBUILD