# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the workflow will run
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          mkdir ./build
          cd ./build
          pacman -Sy asp base-devel --noconfirm
          asp update linux
          asp export linux
          patch ./linux/PKGBUILD ../pkgbuild.patch
      - run: cat ./build/linux/PKGBUILD