# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the workflow will run
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          mkdir ./build
          cd ./build
          pacman -Sy asp git patch --noconfirm
          asp update linux
          asp export linux
          patch ./linux/PKGBUILD ../removedocs.patch
          patch ./linux/PKGBUILD ../pkgbuild.patch
          cp ../beacon_timeout.patch ./linux/
      - run: cat build/linux/PKGBUILD
      - name: Makepkg Build and Check
        id: makepkg
        uses: edlanglois/pkgbuild-action@v1
        with:
          pkgdir: build/linux
          makepkgArgs: "-s"
      - run: echo "done"
      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: build/linux/linux-beacon*