# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the workflow will run
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - run: mkdir ~/build/
      - run: cd ~/build/
      - run: pacman -Sy asp base-devel --noconfirm
      - run: asp update linux
      - run: asp export linux
      - run: sed -i 's/pkgbase=linux/pkgbase=linux-beacon/' linux/config/PKGBUILD
      - run: cat linux/config/PKGBUILD
