# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the workflow will run
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - run: useradd --shell /usr/bin/false build
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          mkdir ./build
          cd ./build
          pacman -Sy asp base-devel --noconfirm
          asp update linux
          asp export linux
          patch ./linux/PKGBUILD ../removedocs.patch
          patch ./linux/PKGBUILD ../pkgbuild.patch
          cp ../beacon_timeout.patch .
      - run: cat build/linux/PKGBUILD
      - run: | 
          chown -R build /__w
          sudo -u build makepkg -s
        working-directory: build
      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: ./build/linux/linux-beacon*